### ISSUE TITLE
Issues with "private access"

### ISSUE THREAD

**Issue by Allomere** [ToMe25/Better-Shields#1]
Hey, im fearly new to modding minecraft and am very grateful for those that make their mod's code opensource, at the moment  my main "material" for learning how to code is analysing how other's code work, i wanted to understand how to create modded shields, so i needed to thank you!
I imported the source of Better-Shields and overlaped it on a forge mdk for the same version, i had some problems trying to add JEI dependencie on build.gradle and was able to figure it out after some time.

But now i'm stuck not beeing able to build it because of some "private/protected access to ItemStackTileEntityRenderer.java"
example:
![image](https://user-images.githubusercontent.com/71918599/104217340-0a158f00-541a-11eb-9579-593b90928fa1.png)
Did you encounter the same problem when building the Original mod? and if not, do you know what i should do to fix that?

**Comment by ToMe25** [comment]
[This line](https://github.com/ToMe25/Better-Shields/blob/1.16.3/src/main/resources/META-INF/accesstransformer.cfg#L2) in the access transformer should normally prevent that issue, no idea why it isn't applied correctly for you.
Try running `gradlew idea` a few more times, and click refresh gradle, that should hopefully fix this.

**Comment by Allomere** [comment]
Oh, it looks like i ended up deleting :
`    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')`
from build.gradle when i was cleaning the comment lines, thank you!

**Comment by ToMe25** [comment]
glad it works now :)
